#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the terms found in the LICENSE file in the root of this source tree.
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface MME service
#   Valid for Ubuntu-18.04 (bionic)
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-mme-builder

ARG EURECOM_PROXY

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && DEBIAN_FRONTEND=noninteractive apt-get install --yes \
    apt-utils \
    psmisc \
    git

# Some GIT configuration command quite useful
RUN /bin/bash -c "if [[ -v EURECOM_PROXY ]]; then git config --global http.proxy $EURECOM_PROXY; fi"
RUN git config --global https.postBuffer 123289600
RUN git config --global http.sslverify false

# Copy source from local workspace
WORKDIR /openair-mme
COPY ./ /openair-mme

# Installing and Building MME
WORKDIR /openair-mme/scripts
RUN ./build_mme --check-installed-software --force
RUN ./build_mme --clean --build-type Release --Verbose

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-mme
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && DEBIAN_FRONTEND=noninteractive apt-get install --yes \
    psmisc \
    openssl \
    net-tools \
    bc \
    tshark \
    libsctp1 \
    libconfig9 \
    libidn11 \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-mme/bin
COPY --from=oai-mme-builder /openair-mme/build/mme/build/mme oai_mme
COPY --from=oai-mme-builder /openair-mme/scripts/entrypoint.sh .

COPY --from=oai-mme-builder /usr/local/lib/libfd* /usr/local/lib/
COPY --from=oai-mme-builder /usr/local/lib/freeDiameter/* /usr/local/lib/freeDiameter/
COPY --from=oai-mme-builder /usr/local/lib/liblfds* /usr/local/lib/

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-mme/etc
COPY --from=oai-mme-builder /openair-mme/etc/mme.conf .
RUN sed -i -e 's#freeDiameter/##' mme.conf
COPY --from=oai-mme-builder /openair-mme/etc/mme_fd.sprint.conf mme_fd.conf
RUN sed -i -e "s#@PREFIX@/freeDiameter#@PREFIX@#g" mme_fd.conf

# Copy the certificate generation script
WORKDIR /openair-mme/scripts
COPY --from=oai-mme-builder /openair-mme/scripts/check_mme_s6a_certificate .
RUN sed -i -e "s@^.*THIS_SCRIPT_PATH@#@" -e "s@\$SUDO@@" check_mme_s6a_certificate
RUN sed -i -e "s@echo_error@echo@" -e "s@echo_success@echo@" -e "s@echo_warning@echo@" check_mme_s6a_certificate

WORKDIR /openair-mme
RUN openssl rand -out /root/.rnd 128

# expose ports
EXPOSE 3870/tcp 5870/tcp 2123/udp

CMD ["/openair-mme/bin/oai_mme", "-c", "/openair-mme/etc/mme.conf"]
ENTRYPOINT ["/openair-mme/bin/entrypoint.sh"]
